/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author dara
 */
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.util.Arrays;
import javax.swing.JOptionPane;
public class SIGNUP extends javax.swing.JFrame {

    /**
     * Creates new form SIGNUP
     */
    public SIGNUP() {
        initComponents();
        this.setTitle("SIGN UP PAGE");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tfname = new javax.swing.JTextField();
        tfusername = new javax.swing.JTextField();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        tfphonenumber = new javax.swing.JTextField();
        tfpassword = new javax.swing.JPasswordField();
        tfconfirmpassword = new javax.swing.JPasswordField();
        jRadioButton3 = new javax.swing.JRadioButton();
        tfemailid = new javax.swing.JTextField();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        tfsection = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        tfyear1 = new javax.swing.JTextField();
        tfregister = new javax.swing.JButton();
        tfbranch = new javax.swing.JTextField();
        tfloggedas = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        jLabel8.setText("jLabel8");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(300, 300, 300, 300));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PHONE-NUMBER");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 170, 160, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("E-MAIL ID");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 210, 160, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("LOGGED AS");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 140, 160, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("PASSWORD");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 250, 160, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("CONFIRM-PASSWORD");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 290, 160, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("SECTION");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(10, 410, 160, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("USERNAME");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(10, 90, 160, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("BRANCH");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(10, 360, 160, 30);

        tfname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfnameActionPerformed(evt);
            }
        });
        getContentPane().add(tfname);
        tfname.setBounds(260, 60, 250, 30);

        tfusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfusernameActionPerformed(evt);
            }
        });
        getContentPane().add(tfusername);
        tfusername.setBounds(260, 100, 250, 30);

        jRadioButton2.setText("FACULTY");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(350, 140, 95, 23);

        jRadioButton1.setText("STUDENT");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(260, 140, 71, 23);

        tfphonenumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfphonenumberActionPerformed(evt);
            }
        });
        getContentPane().add(tfphonenumber);
        tfphonenumber.setBounds(270, 170, 250, 30);
        getContentPane().add(tfpassword);
        tfpassword.setBounds(270, 250, 250, 30);

        tfconfirmpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfconfirmpasswordActionPerformed(evt);
            }
        });
        getContentPane().add(tfconfirmpassword);
        tfconfirmpassword.setBounds(270, 290, 250, 30);

        jRadioButton3.setText("CSE");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton3);
        jRadioButton3.setBounds(270, 330, 50, 23);
        getContentPane().add(tfemailid);
        tfemailid.setBounds(270, 210, 250, 30);

        jRadioButton4.setText("IT");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton4);
        jRadioButton4.setBounds(330, 330, 40, 23);

        jRadioButton5.setText("EEE");
        jRadioButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton5);
        jRadioButton5.setBounds(380, 330, 50, 23);

        jRadioButton6.setText("ECE");
        jRadioButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton6);
        jRadioButton6.setBounds(440, 330, 50, 23);

        jRadioButton7.setText("MECH");
        jRadioButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton7);
        jRadioButton7.setBounds(500, 330, 60, 23);

        jRadioButton8.setText("CIVIL");
        jRadioButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton8);
        jRadioButton8.setBounds(570, 330, 60, 23);

        tfsection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfsectionActionPerformed(evt);
            }
        });
        getContentPane().add(tfsection);
        tfsection.setBounds(270, 410, 250, 30);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("YEAR");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(20, 460, 160, 30);

        tfyear1.setToolTipText("");
        tfyear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfyear1ActionPerformed(evt);
            }
        });
        getContentPane().add(tfyear1);
        tfyear1.setBounds(270, 460, 250, 30);

        tfregister.setText("REGISTER");
        tfregister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfregisterActionPerformed(evt);
            }
        });
        getContentPane().add(tfregister);
        tfregister.setBounds(300, 510, 90, 23);

        tfbranch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfbranchActionPerformed(evt);
            }
        });
        getContentPane().add(tfbranch);
        tfbranch.setBounds(270, 360, 250, 30);
        getContentPane().add(tfloggedas);
        tfloggedas.setBounds(450, 140, 180, 30);

        jTextField7.setText("jTextField7");
        getContentPane().add(jTextField7);
        jTextField7.setBounds(460, 140, 61, 20);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("SIGN UP PAGE");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(120, 14, 210, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("NAME");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 60, 120, 30);
        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 10, 10);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Documents\\NetBeansProjects\\MINIPROJECT\\src\\bluenow.jpg")); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 730, 560);

        pack();
    }// </editor-fold>                        

    private void jRadioButton8ActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
         tfbranch.setText("CIVIL");
       
    }                                             

    private void tfconfirmpasswordActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        // TODO add your handling code here:
    }                                                 

    private void tfsectionActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
                tfloggedas.setText("FACULTY");
    }                                             

    private void tfusernameActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void tfnameActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
    }                                      

    private void tfregisterActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        String name=tfname.getText();
        String username=tfusername.getText();
        String loggedas=tfloggedas.getText();
        String phonenumber=tfphonenumber.getText();
        String emailid=tfemailid.getText();
        String password=Arrays.toString(tfpassword.getPassword());
        String confirmpassword=Arrays.toString(tfconfirmpassword.getPassword());
        String branch=tfbranch.getText();
        String section=tfsection.getText();
        String year=tfyear1.getText();

        
            
        if(loggedas.equals("FACULTY"))
        {
            try
            {
                
                FileWriter f =new FileWriter("C:\\Users\\User\\Documents\\NetBeansProjects\\MINIPROJECT\\profile.txt");
                BufferedWriter b=new BufferedWriter(f);
                b.write("NAME"+" "+name);
                b.newLine();
                b.write("USERNAME"+" "+username);
                b.newLine();
                b.write("LOGGEDAS"+" "+loggedas);
                b.newLine();
                b.write("PHONENUMBER"+" "+phonenumber);
                b.newLine();
                b.write("EMAILID"+" "+emailid);
                b.newLine();
                b.write("BRANCH"+" "+branch);
                b.newLine();
                b.write("SECTION"+" "+section);
                b.newLine();
                b.write("YEAR"+" "+year);
                b.newLine();
                b.close();
                
                
                new facultypage().setVisible(true);
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(this,"ERROR");
            }
        }
        
        if(loggedas.equals("STUDENT"))
        {
        try
        {
            File file1=new File("C:\\Users\\User\\Documents\\NetBeansProjects\\MINIPROJECT\\profile1.txt");
            FileWriter f1 =new FileWriter(file1);
            BufferedWriter b1 = new BufferedWriter(f1);
            b1.write("NAME"+" "+name);
            b1.newLine();
            b1.write("USERNAME"+" "+username);
            b1.newLine();
            b1.write("LOGGEDAS"+" "+loggedas);
            b1.newLine();
            b1.write("PHONENUMBER"+" "+phonenumber);
            b1.newLine();
            b1.write("EMAILID"+" "+emailid);
            b1.newLine();
            b1.write("BRANCH"+" "+branch);
            b1.newLine();
            b1.write("SECTION"+" "+section);
            b1.newLine();
            b1.write("YEAR"+" "+year);
            b1.newLine();
            b1.close();
            new studentpage().setVisible(true);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,"ERROR");
        }
        }
       
    }                                          
    
    private void tfyear1ActionPerformed(java.awt.event.ActionEvent evt) {                                        
            
    }                                       

    private void tfbranchActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
        tfloggedas.setText("STUDENT");
    }                                             

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
        tfbranch.setText("CSE");
    }                                             

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
        tfbranch.setText("IT");
    }                                             

    private void jRadioButton5ActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
        tfbranch.setText("EEE");
    }                                             

    private void jRadioButton6ActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
        tfbranch.setText("ECE");
    }                                             

    private void jRadioButton7ActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
        tfbranch.setText("MECH");
    }                                             

    private void tfphonenumberActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    }                                             

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SIGNUP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SIGNUP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SIGNUP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SIGNUP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new SIGNUP().setVisible(true);
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JTextField jTextField7;
    public static javax.swing.JTextField tfbranch;
    private javax.swing.JPasswordField tfconfirmpassword;
    public static javax.swing.JTextField tfemailid;
    public static javax.swing.JTextField tfloggedas;
    public static javax.swing.JTextField tfname;
    private javax.swing.JPasswordField tfpassword;
    public static javax.swing.JTextField tfphonenumber;
    private javax.swing.JButton tfregister;
    public static javax.swing.JTextField tfsection;
    public static javax.swing.JTextField tfusername;
    public static javax.swing.JTextField tfyear1;
    // End of variables declaration                   
}
