import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author dara
 */
public class studentpage extends javax.swing.JFrame {

    private Object jLabel4;
    private Object jLabel5;

    /**
     * Creates new form studentpage
     */
    public studentpage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButtonprofile = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jbuttonhelp1 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("STUDENT PAGE");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(90, 30, 330, 30);

        jButtonprofile.setText("PROFILE");
        jButtonprofile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonprofileActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonprofile);
        jButtonprofile.setBounds(30, 100, 90, 23);

        jButton2.setText("STUDY MATERIALS");
        getContentPane().add(jButton2);
        jButton2.setBounds(200, 100, 130, 23);

        jButton3.setText("ASK DOUBTS");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(410, 90, 95, 23);

        jButton4.setText("TODO");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(830, 90, 61, 23);

        jbuttonhelp1.setText("HELP");
        jbuttonhelp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonhelp1ActionPerformed(evt);
            }
        });
        getContentPane().add(jbuttonhelp1);
        jbuttonhelp1.setBounds(1020, 90, 57, 23);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("jLabel13");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(30, 150, 190, 30);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("jLabel14");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(30, 190, 190, 30);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("jLabel12");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(30, 240, 190, 30);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("jLabel15");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(30, 300, 190, 30);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("jLabel16");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(30, 350, 190, 30);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("jLabel17");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(30, 410, 190, 30);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setText("jLabel18");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(30, 470, 190, 30);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(51, 51, 51));
        jLabel19.setText("jLabel19");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(30, 530, 190, 30);

        jTextField1.setBackground(new java.awt.Color(0, 0, 0));
        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setText("jTextField1");
        getContentPane().add(jTextField1);
        jTextField1.setBounds(390, 150, 160, 360);

        jButton1.setText("VIEW ANSWERS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(600, 90, 130, 23);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(590, 150, 170, 350);

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(810, 150, 160, 350);

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Documents\\NetBeansProjects\\MINIPROJECT\\src\\bluenow.jpg")); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 1080, 540);

        pack();
    }// </editor-fold>                        

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                         
      String doubt=jTextField1.getText();
      try
      {
          File f1 = new File("C:\\Users\\User\\Documents\\NetBeansProjects\\MINIPROJECT\\projects.txt");
         FileWriter file=new FileWriter(f1);
         BufferedWriter b=new BufferedWriter(file);
         b.write("doubt"+" "+doubt);
         b.close();
         
        new facultypage().setVisible(true);
      }
      catch(Exception e)
      {
          JOptionPane.showMessageDialog(this,"ERROR");
      }
        
    }                                        

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
          try
      {
         File file=new File("C:\\Users\\User\\Documents\\NetBeansProjects\\MINIPROJECT\\profile.txt");
         FileReader f=new FileReader(file);
         BufferedReader b=new BufferedReader(f);
         String read;
         while((read=b.readLine())!=null)
         {
            int length=read.length();
            int index=read.indexOf(" ");
            String str=read.substring(0,index);
            String strr=read.substring(index+1,length);
            if(str.equals("assignment"))
            {
                jLabel3.setText(strr);
               
            }
         }
         b.close();
      }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,"ERROR");
        }
         
    }                                        

    private void jbuttonhelp1ActionPerformed(java.awt.event.ActionEvent evt) {                                             
      JOptionPane.showMessageDialog(this,"use profile for viewing it,\n use study materials for viewing your materials posted,\nusedoubts seesion to ask doubts,\nview todo to complete your assinged works");
    
    }                                            

    private void jButtonprofileActionPerformed(java.awt.event.ActionEvent evt) {                                               
      try
      {
         File  file1=new File("C:\\Users\\User\\Documents\\NetBeansProjects\\MINIPROJECT\\profile1.txt");
         FileReader f1=new FileReader(file1);
         BufferedReader b1=new BufferedReader(f1);
         String read1;
         while((read1=b1.readLine())!=null)
         {
            int length1=read1.length();
            int index1=read1.indexOf(" ");
            String str1=read1.substring(0,index1);
            String strr1=read1.substring(index1+1,length1);
            if(str1.equals("NAME"))
            {
                jLabel13.setText(strr1);
               
            }
            if(str1.equals("USERNAME"))
            {
                jLabel14.setText(strr1);
                
            }
            if(str1.equals("LOGGEDAS "))
            {
                jLabel12.setText(strr1);
                
            }
            if(str1.equals("PHONENUMBER"))
            {
                jLabel15.setText(strr1);

            }
            if(str1.equals("EMAILID"))
            {
                jLabel16.setText(strr1);
               
            }
            if(str1.equals("BRANCH"))
            {
                jLabel17.setText(strr1);

            }
            if(str1.equals("SECTION"))
            {
                jLabel18.setText(strr1);
             
            }
            if(str1.equals("YEAR"))
            {
                jLabel19.setText(strr1);

            } 
         
        
         }
          b1.close();
      }
      catch(Exception e)
      {
          JOptionPane.showMessageDialog(this,"error");
      }

       
  
      
      
    }                                              

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        try
      {
         File file=new File("C:\\Users\\User\\Documents\\NetBeansProjects\\MINIPROJECT\\profile.txt");
         FileReader f=new FileReader(file);
         BufferedReader b=new BufferedReader(f);
         String read;
         while((read=b.readLine())!=null)
         {
            int length=read.length();
            int index=read.indexOf(" ");
            String str=read.substring(0,index);
            String strr=read.substring(index+1,length);
            if(str.equals("answer"))
            {
                jLabel6.setText(strr);
               
            }
         }
         b.close();
      }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,"ERROR");
        }
        
            
    }                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(studentpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(studentpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(studentpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(studentpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new studentpage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButtonprofile;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton jbuttonhelp1;
    // End of variables declaration                   
}
